language: python
python:
    - 3.9
    - 3.8
    - 3.7

install: "make"

script:
    - make test-all

addons:
    sonarcloud:
        organization: "devwhyqueue-github"
        token: "$SONAR_TOKEN"

after_success:
    - sonar-scanner

jobs:
    include:
        -   stage: deploy
            python: 3.9
            install: skip
            script: skip
            after_success: skip
            deploy:
                provider: pypi
                username: "__token__"
                password: "$PYPI_TOKEN"
                distributions: sdist bdist_wheel
                on:
                    tags: true
