language: python
python:
  - 3.9
  - 3.8
  - 3.7
  
addons:
  sonarcloud:
    organization: "devwhyqueue-github"
    token: "$SONAR_TOKEN"

install: "make"

script:
  - make test-all
  - sonar-scanner
