name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [ 3.7, 3.8, 3.9 ]
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install dependencies
                run: make
            -   name: Run tests
                run: make test-all-ci
            -   name: Save coverage (only Python 3.9)
                uses: actions/upload-artifact@master
                if: ${{ matrix.python == 3.9 }}
                with:
                    name: coverage
                    path: coverage.xml

    sonarcloud:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Get coverage
                uses: actions/download-artifact@master
                with:
                    name: coverage
            -   name: SonarCloud Scan
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
